### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by princessAg** [DoF-6413/SummerSwerve2023#13]
- [x] Physical 
- [x] A Simulated version
- [ ] Motion Profiled (and tuned)

**Comment by El1zabethS** [comment]
Is created with no motion profiling, not including limit switches. Update carriage mass

**Comment by El1zabethS** [comment]
Motors: 2 Falcon500s
2 Limit switches at Bottom
Gear Ratio: 7

**Comment by El1zabethS** [comment]
not including motion profiling, going under new issue
